#pragma once
/////////////////////////////////////////////
// Medieval Version 1.5.0.4
/////////////////////////////////////////////
#include "UE4/SDK.h"

#include "BP_Enums.h"
#include "BP_Structs.h"

#include "Medieval_Dynasty/Medieval_Dynasty_SDK.h"

#include "AIC_Husbandry/AIC_Husbandry_SDK.h"
#include "AIC_NPC/AIC_NPC_SDK.h"
#include "AIC_NPC_Bandits/AIC_NPC_Bandits_SDK.h"
#include "BP_AnimalBase/BP_AnimalBase_SDK.h"
#include "BP_AnimalsManager/BP_AnimalsManager_SDK.h"
#include "BP_BaseCharacter/BP_BaseCharacter_SDK.h"
#include "BP_Camera/BP_Camera_SDK.h"
#include "BP_CameraManager/BP_CameraManager_SDK.h"
#include "BP_CharacterRelationsComponent/BP_CharacterRelationsComponent_SDK.h"
#include "BP_CharacterStatsComponent/BP_CharacterStatsComponent_SDK.h"
#include "BP_DataManager/BP_DataManager_SDK.h"
#include "BP_EventManager/BP_EventManager_SDK.h"
#include "BP_FlyingAnimalBase/BP_FlyingAnimalBase_SDK.h"
#include "BP_MasterHoldableItem/BP_MasterHoldableItem_SDK.h"
#include "BP_MasterItem/BP_MasterItem_SDK.h"
#include "BP_MasterManager/BP_MasterManager_SDK.h"
#include "BP_NPC/BP_NPC_SDK.h"
#include "BP_NPC_Bandit/BP_NPC_Bandit_SDK.h"
#include "BP_NPC_Manager/BP_NPC_Manager_SDK.h"
#include "BP_PlayerBuildingComponent/BP_PlayerBuildingComponent_SDK.h"
#include "BP_PlayerCharacter/BP_PlayerCharacter_SDK.h"
#include "BP_POI_Manager/BP_POI_Manager_SDK.h"
#include "BP_POI_Spawner/BP_POI_Spawner_SDK.h"
#include "BP_QuestManager/BP_QuestManager_SDK.h"
#include "BP_SystemsManager/BP_SystemsManager_SDK.h"
#include "BP_TimeManager/BP_TimeManager_SDK.h"
#include "BP_WeatherComponent/BP_WeatherComponent_SDK.h"
#include "BP_WeatherManager/BP_WeatherManager_SDK.h"
#include "F_Medieval/F_Medieval_SDK.h"
#include "GI_MedievalDynasty/GI_MedievalDynasty_SDK.h"
#include "GM_MedievalDynasty/GM_MedievalDynasty_SDK.h"
#include "GS_GameState/GS_GameState_SDK.h"
#include "InventoryComponent/InventoryComponent_SDK.h"
#include "PC_Player/PC_Player_SDK.h"