#pragma once
/////////////////////////////////////////////
// Medieval Version 1.5.0.4
/////////////////////////////////////////////

#include "UE_LOG.h"

#include "Math/Vector.h"
#include "Math/Color.h"
#include "Math/Transform.h"
#include "Math/Box.h"
#include "Math/Plane.h"
#include "Math/Quat.h"

#include "Containers/Array.h"
#include "Containers/Pointers.h"
#include "Containers/String.h"
#include "Containers/Templates.h"
#include "Containers/Text.h"

#include "CoreUObject/NamePool.h"
#include "CoreUObject/ObjectsArray.h"
#include "CoreUObject/Object.h"
#include "CoreUObject/CoreTypes.h"
#include "CoreUObject/Class.h"
#include "CoreUObject/UnrealType.h"
#include "CoreUObject/Stack.h"

#include "Engine/Structs.h"
#include "Engine/Actor.h"
#include "Engine/GameInstance.h"
#include "Engine/GameMode.h"
#include "Engine/GamePlayStatics.h"
#include "Engine/GameState.h"
#include "Engine/Level.h"
#include "Engine/Pawn.h"
#include "Engine/PlayerController.h"
#include "Engine/UserDefinedEnum.h"
#include "Engine/UserDefinedStruct.h"
#include "Engine/World.h"
#include "Engine/StringTable.h"
#include "Engine/DataTable.h"
#include "Engine/Controller.h"
#include "Engine/SkeletalMesh.h"
#include "Engine/MaterialInterface.h"
#include "Engine/MaterialInstance.h"
#include "Engine/PrimitiveComponent.h"
#include "Engine/ActorComponent.h"
#include "Engine/MeshComponent.h"
#include "Engine/SceneComponent.h"
#include "Engine/SkeletalMeshComponent.h"
#include "Engine/SkinnedMeshComponent.h"
#include "Engine/SpringArmComponent.h"
#include "Engine/StaticMeshComponent.h"
#include "Engine/BlueprintFunctionLibrary.h"
#include "Engine/BlueprintGeneratedClass.h"
#include "Engine/BlueprintMapLibrary.h"
#include "Engine/BlueprintPathsLibrary.h"
#include "Engine/BlueprintPlatformLibrary.h"
#include "Engine/BlueprintSetLibrary.h"
#include "Engine/KismetArrayLibrary.h"
#include "Engine/KismetGuidLibrary.h"
#include "Engine/KismetInputLibrary.h"
#include "Engine/KismetInternationalizationLibrary.h"
#include "Engine/KismetMaterialLibrary.h"
#include "Engine/KismetMathLibrary.h"
#include "Engine/KismetRenderingLibrary.h"
#include "Engine/KismetStringLibrary.h"
#include "Engine/KismetSystemLibrary.h"
#include "Engine/KismetTextLibrary.h"


#include "AIModule/AIController.h"

#include "PropertyPath/PropertyPath_SDK.h"
#include "SlateCore/SlateCore_SDK.h"
#include "Slate/Slate_SDK.h"
#include "Chaos/Chaos_SDK.h"
#include "PhysicsCore/PhysicsCore_SDK.h"
#include "MovieScene/MovieScene_SDK.h"
#include "MovieSceneTracks/MovieSceneTracks_SDK.h"
#include "UMG/UMG_SDK.h"
#include "AIModule/Structs.h"
#include "AdsMountingSystem/AdsMountingSystem_SDK.h"
