#pragma once
/////////////////////////////////////////////
// Package MovieScene
// Classes: 58
// Enums: 15
// Structs: 104
// Objects: 261
/////////////////////////////////////////////


#include "Structs.h"

#include "MovieSceneSignedObject.h"
#include "MovieSceneSequence.h"
//#include "MovieSceneSequencePlayer.h"
#include "MovieSceneSection.h"
//#include "MovieSceneSubSection.h"
#include "MovieSceneEntitySystem.h"
#include "MovieSceneTrack.h"
#include "MovieSceneNameableTrack.h"
//#include "MovieSceneSubTrack.h"
//#include "MovieSceneCustomClockSource.h"
//#include "MovieSceneDeterminismSource.h"
//#include "MovieSceneEntityProvider.h"
//#include "MovieSceneEvaluationHook.h"
//#include "MovieScenePlaybackClient.h"
//#include "MovieSceneTrackTemplateProducer.h"
//#include "NodeAndChannelMappings.h"
//#include "MovieSceneNodeGroup.h"
//#include "MovieSceneNodeGroupCollection.h"
#include "MovieScene.h"
//#include "MovieSceneBindingOverrides.h"
//#include "MovieSceneBindingOwnerInterface.h"
//#include "MovieSceneBlenderSystem.h"
//#include "MovieSceneBoolSection.h"
//#include "MovieSceneEntityInstantiatorSystem.h"
//#include "MovieSceneGenericBoundObjectInstantiator.h"
//#include "MovieSceneBoundSceneComponentInstantiator.h"
//#include "MovieSceneSceneComponentImpersonator.h"
//#include "MovieSceneCompiledData.h"
//#include "MovieSceneCompiledDataManager.h"
//#include "MovieSceneFloatDecomposer.h"
//#include "MovieSceneBuiltInEasingFunction.h"
//#include "MovieSceneEasingExternalCurve.h"
//#include "MovieSceneEasingFunction.h"
//#include "MovieSceneEntitySystemLinker.h"
//#include "MovieSceneEvalTimeSystem.h"
//#include "MovieSceneEvaluationHookSystem.h"
//#include "MovieSceneFolder.h"
//#include "MovieSceneHookSection.h"
//#include "MovieSceneKeyProxy.h"
//#include "MovieSceneMasterInstantiatorSystem.h"
//#include "MovieScenePreAnimatedStateSystemInterface.h"
//#include "MovieSceneCachePreAnimatedStateSystem.h"
//#include "MovieSceneRestorePreAnimatedStateSystem.h"
//#include "MovieSceneSequenceActor.h"
//#include "MovieSceneSequenceTickManager.h"
//#include "MovieSceneSpawnablesSystem.h"
//#include "MovieSceneSpawnSection.h"
//#include "MovieSceneSpawnTrack.h"
//#include "TestMovieSceneTrack.h"
//#include "TestMovieSceneSection.h"
//#include "TestMovieSceneSequence.h"
//#include "TestMovieSceneSubTrack.h"
//#include "TestMovieSceneSubSection.h"
//#include "TestMovieSceneEvalHookTrack.h"
//#include "TestMovieSceneEvalHookSection.h"
//#include "MovieSceneTrackInstance.h"
//#include "MovieSceneTrackInstanceInstantiator.h"
//#include "MovieSceneTrackInstanceSystem.h"
